### ISSUE TITLE
Starting handshake loop taking very long

### ISSUE THREAD

**Issue by ellwoodb** [qwertyquerty/pypresence#94] opened 2020-12-03 18:23 UTC
The `RPC.connect()` command is taking a lot of time (like 5 Seconds).

**Comment by KhushC-03** [comment] 2021-01-08 18:45
Mine takes even longer sometimes

**Comment by Hunter2807** [comment] 2021-02-10 10:25
@ellwoodb if the issue is fixed, then close this issue, else join the official discord server here and ask for help --> https://discord.gg/FSQmzwj3

**Comment by LewdNeko** [comment] 2021-06-03 22:23
Will re-open if more information provided.

**Closed by LewdNeko** 2021-06-03 22:23 UTC
