### ISSUE TITLE
Need Help - noob - RCP not updating unless I restart the script

### ISSUE THREAD

**Issue by pir8radio** [qwertyquerty/pypresence#141] opened 2021-10-23 15:41 UTC
sorry to post as an issue, I couldn't come across a good forum or anything..   I must be missing something here..   The below runs and sets RCP on discord, but after the 30 seconds it doesn't update on discord, but does update on the python console screen.    If i kill and restart then discord updates.   any idea what i'm doing wrong here?

`from pypresence import Presence
import time
import json
import requests

while True:
 url = 'https://apiJSONcall.com/api'
 reply = ''
 heightInt = ''
 heightMath = ''
 heightStr = ''
 
 response = requests.get(url).json()
 reply = response
 heightInt = (reply['miningInfo']['height'])
 heightMath = 941100 -heightInt
 heightStr = str(heightMath)
 
 client_id = '90129XXXXXXX' #Put your client ID here
 RPC = Presence(client_id,pipe=0) 
 RPC.connect() 

 print(RPC.update(state=""+ heightStr + " Blocks to go!", details="Hard Fork Countdown", large_image="HardFork", small_image="NAME OF SMALL IMAGE HERE", large_text="LARGE IMAGE TEXT HERE", start=time.time()))  # Set the presence

 
 time.sleep(30) `

**Comment by Aethese** [comment] 2021-11-01 14:30
its your while True loop. put that into a function instead of a loop and you're good to go

**Comment by Hunter2807** [comment] 2021-11-04 15:16
Hey @pir8radio please close this if the issue is solved or ask in the Discord Server (;

**Closed** 2021-11-12 20:37 UTC
